<?php 
$title='Delete User';
?>

<?php 
  $url = $this->url('user', array('action' => 'delete','id' => $this->id));
?>
<h1><?php echo $this->escapeHtml($title)?></h1>

<p> Are you sure that you want to delete
	<?php echo $this->id;?>
</p>


<form action="<?php echo $url; ?>" method="post">
<div>
<input type="hidden" name="id" value="<?php echo (int) $this->id; ?>" />
<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>
</form>