<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('2015 '. $this->translate('Booking My Car'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
						->prependStylesheet($this->basePath('css/mycss.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>
                        
                        
	  <!-- Scripts -->
	  <?php
	    echo $this->HeadScript()->appendFile('angular/user/user.js','text/javascript');
	   ?>
	   <?php
	    echo $this->HeadScript()->appendFile('https://ajax.googleapis.com/ajax/libs/angularjs/1.3.4/angular.min.js');
	   ?>
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
         
    </head>
    
    
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Booking My Car"/>&nbsp;<?php echo $this->translate('Booking My Car') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav"> 
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                        <li class="active"><a href="<?php echo $this->url('user') ?>"><?php echo $this->translate('My Space') ?></a></li>
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Location') ?></a></li>
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Agencies') ?></a></li>
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Current Traffic') ?></a></li>
                        <li class="active"><a href="<?php echo $this->url('user') ?>"><?php echo $this->translate('Blog') ?></a></li>
                        <li class="active"><a href="<?php echo $this->url('user',array('controller'=>'user','action'=>'register'));?>"><?php echo $this->translate('Sign in') ?></a></li>       
                        <li class="active text-right"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Sign up') ?></a></li>
                        <li class="active text-right"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Forget password') ?></a></li>
                        <li class="active text-right"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Forget account') ?></a></li>
                        
                       <!-- <li class="active"><a href="<?php echo $this->url('album') ?>"><?php echo $this->translate('Album') ?></a></li>-->
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container" >
                 <?php echo $this->content; ?>
	        <hr>
        </div> <!-- /container -->
       
            <footer>
                <p>&copy; 2015 - <?php echo date('Y') ?> by The World of Developers Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
