<?php echo $this->partial('top.phtml'); ?>
<!--
<div class="row">
	 <div class="col-sm-6 col-md-4 col-md-offset-4">
<div class="account-register">
<div class="register">
	
<form class="form-horizontal" role="form" name="registerform"   data-ng-app="myapp" data-ng-controller="RegisterUser">
		  <h4 class="text-center title">{{person.title}}</h4>
								 <div class="form-group">
								 	 <label class="control-label">{{ person.name }}</label>
								 	 <input type="text" class="form-control"   placeholder="Enter your name" required=" its is required"/>
								 </div>
								 
								 <div class="form-group">
								 	 <label class="control-label">{{person.username}}</label>
								 	 <input type="text" name="surname" class="form-control" placeholder="Enter your surname" required />
								 </div>
								 
								 <div class="form-group">
								 	<label class="control-label">{{person.identifiant_type }}</label>
								 	 <select name="selectType"  data-ng-model="data.selectType">
								 	 	 <option data-ng-repeat="option in data.availableOptions" value="{{option.name}}">{{option.name}}</option>
								 	 </select><tt hidden>repeatSelect = {{data.selectType}}</tt><br/>
								 </div>
								 
								 <div class="form-group">
								 	<label class="control-label ">{{person.identifiant_number }}</label>
								 	  <input type="text" name="identifynumber" class="form-control" placeholder="Identified Number" required />
								 </div>
								
								 <div class="form-group">
								 	<label class="control-label ">{{person.phone_number }}</label>
								 	  <input type="tel" name="phone_number" class="form-control" placeholder="Phone Number" required="please"/>
								 </div>
								 
								 <div class="form-group">
								 	<label class="control-label ">{{person.email }}</label>
								 	  <input type="email" name="email" class="form-control" placeholder="Email address" required=""/>
								 </div>
								 
								 <div class="form-group">
								 	<label class="control-label">{{person.user_name }}</label>
								 	  <input type="text" name="user_name" class="form-control" placeholder="User Name" required="" />
								 </div>
								 
								  <div class="form-group">
								 	<label class="control-label">{{person.user_password }}</label>
								 	  <input type="password" name="user_password" class="form-control" placeholder="Password" required=""/>
								 </div>
								 
								<div class="form-group">
								<div class="col-xs-6">
							    <label class="checkbox pull-left">
								     <input type="checkbox" value="remerber-me" /> Remerber me!
								</label>
			<button class="btn btn-success"><span class="glyphicon glyphicon-plus-sign"></span> Register</button>
							    </div>
							    </div>
</form>
</div>	
</div>
</div>	
</div>
-->