<?php echo $this->partial('top.phtml'); ?>
<div class="row">
<div class="col-sm-6 col-md-4 col-md-offset-4">
<div class="account-register">
<div class="register">	
<form class="form-horizontal" role="form" name="registerform"  method="post" action="" >
		  <h4 class="text-center title">Sign in</h4>
								
								  <div class="form-group">
								 	<label class="control-label ">Identity Number:</label>
								 	  <input type="text" name="identifynumber" class="form-control" placeholder="Identified Number" required />
								 </div>
								 
								 <div class="form-group">
								 	<label class="control-label">User name:</label>
								 	  <input type="text" name="user_name" class="form-control" placeholder="User Name" required="" />
								 </div>
								 
								  <div class="form-group">
								 	<label class="control-label">Password:</label>
								 	  <input type="password" name="user_password" class="form-control" placeholder="Password" required=""/>
								 </div>
								 
								<div class="form-group">
								<div class="col-xs-6">
							    <label class="checkbox pull-left">
								     <input type="checkbox" value="remerber-me" /> Remerber me!
								</label>
			<button class="btn btn-primary"><span class="glyphicon glyphicon-plus-sign"></span> Sign in</button>
							    </div>
							    </div>
</form>
</div>	
</div>
</div>	
</div>