<div class="row">	
<h1 class="text-center main-text"> <strong>MY SPACE</strong>  </h1>
  <h4 class="text-center"> TRAVEL IN SECURE MY INTERNATIONAL BOOKING CAR  </h4>
  
  
 	<div class="navbar navbar-default navbar-static-top"> 
	 		  <div class="container">
	 		  	
	 		  	   <a href="<?php echo $this->url('cuser',array('controller'=>'cuser','action'=>'index'));?>" class="navbar-brand glyphicon glyphicon-user navsecond">
	 		  	   	  MY SPACE
	 		  	   </a>
	 		  	    
	 		  	    <button class="navbar-toggle" data-toggle="collapse"  data-target=".navHeaderCollapse">
	 		  	    	 <span class="icon-bar"></span>
	 		  	    	 <span class="icon-bar"></span>
	 		  	    	 <span class="icon-bar"></span>
	 		  	    	
	 		  	    </button>
	 		  	     
	 		  	    <div class="collapse navbar-collapse navHeaderCollapse">
	 		  	    	<ul class="nav navbar-nav navbar-right">
	 		  	    		
	 		  	    		  <li ><a href="<?php echo $this->url('cuser',array('controller'=>'cuser','action'=>'signin'));?>"><?php echo $this->translate('Sign in') ?> </a></li>
			 	   	          <li><a href="<?php echo $this->url('cuser',array('controller'=>'cuser','action'=>'signup'));?>"><?php echo $this->translate('Sign up') ?></a></li>
							  <li><a href="<?php echo $this->url('cuser',array('controller'=>'cuser','action'=>'forgetpassword'));?>"><?php echo $this->translate('Forget my password') ?></a></li>
							  <li><a href="<?php echo $this->url('cuser',array('controller'=>'cuser','action'=>'changepaswword'));?>"><?php echo $this->translate('Change my password') ?></a></li>
							  <li><a href="<?php echo $this->url('cuser',array('controller'=>'cuser','action'=>'forgetusername'));?>"><?php echo $this->translate('Forget my account') ?></a></li>
							  <li><a href="<?php echo $this->url('cuser',array('controller'=>'cuser','action'=>'update'));?>"><?php echo $this->translate('Update my information') ?></a></li>
			    	          <li ><a href="<?php echo $this->url('cuser',array('controller'=>'cuser','action'=>'list'));?>"> <?php echo $this->translate('List of Users') ?></a></li>
							
							<!--	<li class="dropdown"> 
								    <a href="<?php echo $this->url('cuser',array('controller'=>'cuser','action'=>'mydata'));?>"  class="dropdown-toggle" data-toggle="dropdown"><?php echo $this->translate('My booking space') ?>
								    <b class="caret"></b> </a>
										<ul class="dropdown-menu">
											<li ><a href="<?php echo $this->url('cuser',array('controller'=>'cuser','action'=>'list'));?>"> <?php echo $this->translate('List of Users') ?></a></li>
											<li ><a href="<?php echo $this->url('cuser',array('controller'=>'cuser','action'=>'adding'));?>"><?php echo $this->translate('Adding Users') ?></a></li>
										</ul>
								</li>-->
	 		  	    	</ul>
	 		  	    </div>
	 		  </div>
	 	</div>
</div>
