<?php echo $this->partial('top.phtml'); ?>
<div class="row">
<div class="col-sm-6 col-md-4 col-md-offset-4">
<div class="account-register">
<div class="register">
	
<form class="form-horizontal" role="form" name="registerform"   data-ng-app="myapp" data-ng-controller="RegisterUser">
		  <h4 class="text-center title">Update Information</h4>
		                         
		                         <div class="form-group">
								 	<label class="control-label">User &nbsp; &nbsp;&nbsp;&nbsp;Type:</label>
								 	 <select name="usertype"  data-ng-model="data.selectType">
								 	 	 <option  value="personal_user">Personal &nbsp;&nbsp;&nbsp;&nbsp;user</option>
								 	     <option  value="Agency">Agency</option>
								 	     </select>
								 </div>
								 
		                         <div class="form-group">
								 	<label class="control-label">Identity Type:</label>
								 	 <select name="selectType"  data-ng-model="data.selectType">
								 	 	 <option  value="Identity Card">Identity Card</option>
								 	     <option  value="Passport">Passport</option>
								 	     <option  value="Student Card">Student Card</option>
								 	     <option  value="Register Number">Register Number</option>
								 	     </select>
								 </div>
								 
								 <div class="form-group">
								 	<label class="control-label ">Identity Number:</label>
								 	  <input type="text" name="identifynumber" class="form-control" placeholder="Identified Number" required />
								 </div>
								 <div class="form-group">
								 	 <label class="control-label">Name</label>
								 	 <input type="text" class="form-control"   placeholder="Enter your name" required=" its is required"/>
								 </div>
								 
								 <div class="form-group">
								 	 <label class="control-label">Surname:</label>
								 	 <input type="text" name="surname" class="form-control" placeholder="Enter your surname" required />
								 </div>
								 
								
								 <div class="form-group">
								 	<label class="control-label ">Phone number:</label>
								 	  <input type="tel" name="phone_number" class="form-control" placeholder="Phone Number" required="please"/>
								 </div>
								 
								 <div class="form-group">
								 	<label class="control-label ">Email:</label>
								 	  <input type="email" name="email" class="form-control" placeholder="Email address" required=""/>
								 </div>
								 
								<div class="form-group">
								<div class="col-xs-6">
			<button class="btn btn-success"><span class="glyphicon glyphicon-refresh"></span> Update</button>
							    </div>
							    </div>
</form>
</div>	
</div>
</div>	
</div>